---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hubin.
--- DateTime: 19-1-25 下午2:49
---

local UseCourier = {}

UseCourier.Name = "Use Courier Action"
UseCourier.NumArgs = 2

-- sAction names a COURIER_ACTION_* constant, such as COURIER_ACTION_TAKE_AND_TRANSFER_ITEMS: fetch the stash,
-- carry it to the hero, then fly home (measured on 6937, docs/VERSION_DIFF.md 3.2).
function UseCourier:Call(bot, sAction)
    if bot:IsIllusion() then return end
    for i = 0, GetNumCouriers() - 1 do
        local courier = GetCourier(i)
        if courier:GetPlayerID() == bot:GetPlayerID() then
            if GetCourierState(courier) ~= COURIER_STATE_DEAD then
                bot:ActionImmediate_Courier(courier, _G[sAction[1]])
            end
            return
        end
    end
end

return UseCourier
