"""Constants mirrored from Valve's dota_shared_enums.proto.

Only the handful the environment needs are kept here, so the package does not
have to compile the (large, frequently changing) shared enums proto.
"""

TEAM_RADIANT = 2
TEAM_DIRE = 3

DOTA_GAMEMODE_AP = 1
DOTA_GAMEMODE_1V1MID = 21

DOTA_GAMERULES_STATE_INIT = 0
DOTA_GAMERULES_STATE_WAIT_FOR_PLAYERS_TO_LOAD = 1
DOTA_GAMERULES_STATE_HERO_SELECTION = 2
DOTA_GAMERULES_STATE_STRATEGY_TIME = 3
DOTA_GAMERULES_STATE_PRE_GAME = 4
DOTA_GAMERULES_STATE_GAME_IN_PROGRESS = 5
DOTA_GAMERULES_STATE_POST_GAME = 6
DOTA_GAMERULES_STATE_DISCONNECT = 7

ACTIONABLE_GAME_STATES = (DOTA_GAMERULES_STATE_PRE_GAME, DOTA_GAMERULES_STATE_GAME_IN_PROGRESS)

HOST_MODE_DEDICATED = 'HOST_MODE_DEDICATED'
HOST_MODE_GUI = 'HOST_MODE_GUI'
HOST_MODE_GUI_MENU = 'HOST_MODE_GUI_MENU'

# CMsgBotWorldState.UnitType
UNIT_TYPE_HERO = 1
UNIT_TYPE_CREEP_HERO = 2
UNIT_TYPE_LANE_CREEP = 3
UNIT_TYPE_JUNGLE_CREEP = 4
UNIT_TYPE_ROSHAN = 5
UNIT_TYPE_TOWER = 6
UNIT_TYPE_BARRACKS = 7
UNIT_TYPE_SHRINE = 8
UNIT_TYPE_FORT = 9
UNIT_TYPE_BUILDING = 10
UNIT_TYPE_COURIER = 11
UNIT_TYPE_WARD = 12

INVALID_HANDLE = 0xFFFFFFFF
